#If debug mode is active, the mod will print the name of any mob killed by the player to console, and will log when items are dropped
debugMode = true
#Items to add, in the form modid:itemName:[nbtfile]:[minStackSize]:[maxStackSize]:[universalChance]:[monsterChance]:[bossChance]:[group1Chance]:[group2Chance]...
#Chances are %
#NBT File is a json file in the "editmobdrops" folder here in config (leave blank for none)
itemsToAdd = []
#Mob groups, in the form [EntityName]:[EntityName]...
mobGroups = []
#Mobs to clear existing drops from
mobsToClear = ["ChickenEntity", "CowEntity", "PigEntity"]
#Single mob items, in the form EntityName:modid:itemName:[nbtfile]:[minStackSize]:[maxStackSize]:[chance]
singleMobItems = ["ChickenEntity:minecraft:chicken::0:1:30", "ChickenEntity:minecraft:feather::1:5:100", "CowEntity:minecraft:beef::0:1:30", "CowEntity:minecraft:leather::1:3:100", "PigEntity:minecraft:porkchop::0:1:30"]

